session_name: unical
start_directory: ./
windows:
  - window_name: nuxt
    layout: tiled
    # shell_command_before:
    #   - cd ~/ # run as a first command in all panes
    panes:
      - bun run dev
      # - echo second pane # pane no. 2
      # - echo third pane # pane no. 3
      # - echo fourth pane # pane no. 4